export default {
    "login": "Deepanshu-5288",
    "id": 40418727,
    "node_id": "MDQ6VXNlcjQwNDE4NzI3",
    "avatar_url": "https://avatars.githubusercontent.com/u/40418727?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Deepanshu-5288",
    "html_url": "https://github.com/Deepanshu-5288",
    "followers_url": "https://api.github.com/users/Deepanshu-5288/followers",
    "following_url": "https://api.github.com/users/Deepanshu-5288/following{/other_user}",
    "gists_url": "https://api.github.com/users/Deepanshu-5288/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Deepanshu-5288/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Deepanshu-5288/subscriptions",
    "organizations_url": "https://api.github.com/users/Deepanshu-5288/orgs",
    "repos_url": "https://api.github.com/users/Deepanshu-5288/repos",
    "events_url": "https://api.github.com/users/Deepanshu-5288/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Deepanshu-5288/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Deepanshu Gupta",
    "company": "Accenture",
    "blog": "",
    "location": "India",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 55,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2018-06-20T05:52:41Z",
    "updated_at": "2022-12-02T17:52:24Z"
  };